package com.proint1.udea.produccion.clases;

// default package
// Generated 10-may-2014 11:58:30 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TbPrdTipoproducionesxcampo generated by hbm2java
 */
public class TbPrdTipoproducionesxcampo implements java.io.Serializable {

	private long nbIdn;
	private TbPrdCampos tbPrdCampos;
	private TbPrdTipoproduccion tbPrdTipoproduccion;
	private String vrAdtusuario;
	private Date dtAdtfecha;
	private Set tbPrdDetalleproducioneses = new HashSet(0);

	public TbPrdTipoproducionesxcampo() {
	}

	public TbPrdTipoproducionesxcampo(long nbIdn, TbPrdCampos tbPrdCampos,
			TbPrdTipoproduccion tbPrdTipoproduccion, String vrAdtusuario,
			Date dtAdtfecha) {
		this.nbIdn = nbIdn;
		this.tbPrdCampos = tbPrdCampos;
		this.tbPrdTipoproduccion = tbPrdTipoproduccion;
		this.vrAdtusuario = vrAdtusuario;
		this.dtAdtfecha = dtAdtfecha;
	}

	public TbPrdTipoproducionesxcampo(long nbIdn, TbPrdCampos tbPrdCampos,
			TbPrdTipoproduccion tbPrdTipoproduccion, String vrAdtusuario,
			Date dtAdtfecha, Set tbPrdDetalleproducioneses) {
		this.nbIdn = nbIdn;
		this.tbPrdCampos = tbPrdCampos;
		this.tbPrdTipoproduccion = tbPrdTipoproduccion;
		this.vrAdtusuario = vrAdtusuario;
		this.dtAdtfecha = dtAdtfecha;
		this.tbPrdDetalleproducioneses = tbPrdDetalleproducioneses;
	}

	public long getNbIdn() {
		return this.nbIdn;
	}

	public void setNbIdn(long nbIdn) {
		this.nbIdn = nbIdn;
	}

	public TbPrdCampos getTbPrdCampos() {
		return this.tbPrdCampos;
	}

	public void setTbPrdCampos(TbPrdCampos tbPrdCampos) {
		this.tbPrdCampos = tbPrdCampos;
	}

	public TbPrdTipoproduccion getTbPrdTipoproduccion() {
		return this.tbPrdTipoproduccion;
	}

	public void setTbPrdTipoproduccion(TbPrdTipoproduccion tbPrdTipoproduccion) {
		this.tbPrdTipoproduccion = tbPrdTipoproduccion;
	}

	public String getVrAdtusuario() {
		return this.vrAdtusuario;
	}

	public void setVrAdtusuario(String vrAdtusuario) {
		this.vrAdtusuario = vrAdtusuario;
	}

	public Date getDtAdtfecha() {
		return this.dtAdtfecha;
	}

	public void setDtAdtfecha(Date dtAdtfecha) {
		this.dtAdtfecha = dtAdtfecha;
	}

	public Set getTbPrdDetalleproducioneses() {
		return this.tbPrdDetalleproducioneses;
	}

	public void setTbPrdDetalleproducioneses(Set tbPrdDetalleproducioneses) {
		this.tbPrdDetalleproducioneses = tbPrdDetalleproducioneses;
	}

}
