// default package
// Generated 10-may-2014 11:58:30 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * TbMicMicrocurriculo generated by hbm2java
 */
public class TbMicMicrocurriculo implements java.io.Serializable {

	private BigDecimal nbMicIdn;
	private TbMicEstadomic tbMicEstadomic;
	private TbMicNucleoacademico tbMicNucleoacademico;
	private TbAdmSemestrexcurso tbAdmSemestrexcurso;
	private TbMicEvaluacion tbMicEvaluacion;
	private TbMicActa tbMicActa;
	private TbMicUnidades tbMicUnidades;
	private String vrAdtusuario;
	private Date dtAdtfecha;
	private String vrMicNombre;
	private String vrMicValidable;
	private Byte nbMicHorasteoricasemanales;
	private Short nbMicHorasterosem;
	private Byte nbMicNumerocreditos;
	private Short nbHorasclasexsemestre;
	private String vrMicCampodeformacion;
	private String vrMicHabilitable;
	private String vrMicClasificable;
	private String vrMicRequisitos;
	private String vrMicCorrequisito;
	private byte nbMicProgram;
	private String vrMicProposito;
	private String vrMicJustificacion;
	private String vrMicObjetivogeneral;
	private String vrMicObjetivosespecificos;
	private String vrMicContenidoresumido;
	private Byte nbMicEstado;
	private String vrMicBibliografia;

	public TbMicMicrocurriculo() {
	}

	public TbMicMicrocurriculo(TbMicEstadomic tbMicEstadomic,
			TbMicNucleoacademico tbMicNucleoacademico,
			TbAdmSemestrexcurso tbAdmSemestrexcurso,
			TbMicEvaluacion tbMicEvaluacion, TbMicActa tbMicActa,
			TbMicUnidades tbMicUnidades, String vrMicNombre, byte nbMicProgram) {
		this.tbMicEstadomic = tbMicEstadomic;
		this.tbMicNucleoacademico = tbMicNucleoacademico;
		this.tbAdmSemestrexcurso = tbAdmSemestrexcurso;
		this.tbMicEvaluacion = tbMicEvaluacion;
		this.tbMicActa = tbMicActa;
		this.tbMicUnidades = tbMicUnidades;
		this.vrMicNombre = vrMicNombre;
		this.nbMicProgram = nbMicProgram;
	}

	public TbMicMicrocurriculo(TbMicEstadomic tbMicEstadomic,
			TbMicNucleoacademico tbMicNucleoacademico,
			TbAdmSemestrexcurso tbAdmSemestrexcurso,
			TbMicEvaluacion tbMicEvaluacion, TbMicActa tbMicActa,
			TbMicUnidades tbMicUnidades, String vrAdtusuario, Date dtAdtfecha,
			String vrMicNombre, String vrMicValidable,
			Byte nbMicHorasteoricasemanales, Short nbMicHorasterosem,
			Byte nbMicNumerocreditos, Short nbHorasclasexsemestre,
			String vrMicCampodeformacion, String vrMicHabilitable,
			String vrMicClasificable, String vrMicRequisitos,
			String vrMicCorrequisito, byte nbMicProgram, String vrMicProposito,
			String vrMicJustificacion, String vrMicObjetivogeneral,
			String vrMicObjetivosespecificos, String vrMicContenidoresumido,
			Byte nbMicEstado, String vrMicBibliografia) {
		this.tbMicEstadomic = tbMicEstadomic;
		this.tbMicNucleoacademico = tbMicNucleoacademico;
		this.tbAdmSemestrexcurso = tbAdmSemestrexcurso;
		this.tbMicEvaluacion = tbMicEvaluacion;
		this.tbMicActa = tbMicActa;
		this.tbMicUnidades = tbMicUnidades;
		this.vrAdtusuario = vrAdtusuario;
		this.dtAdtfecha = dtAdtfecha;
		this.vrMicNombre = vrMicNombre;
		this.vrMicValidable = vrMicValidable;
		this.nbMicHorasteoricasemanales = nbMicHorasteoricasemanales;
		this.nbMicHorasterosem = nbMicHorasterosem;
		this.nbMicNumerocreditos = nbMicNumerocreditos;
		this.nbHorasclasexsemestre = nbHorasclasexsemestre;
		this.vrMicCampodeformacion = vrMicCampodeformacion;
		this.vrMicHabilitable = vrMicHabilitable;
		this.vrMicClasificable = vrMicClasificable;
		this.vrMicRequisitos = vrMicRequisitos;
		this.vrMicCorrequisito = vrMicCorrequisito;
		this.nbMicProgram = nbMicProgram;
		this.vrMicProposito = vrMicProposito;
		this.vrMicJustificacion = vrMicJustificacion;
		this.vrMicObjetivogeneral = vrMicObjetivogeneral;
		this.vrMicObjetivosespecificos = vrMicObjetivosespecificos;
		this.vrMicContenidoresumido = vrMicContenidoresumido;
		this.nbMicEstado = nbMicEstado;
		this.vrMicBibliografia = vrMicBibliografia;
	}

	public BigDecimal getNbMicIdn() {
		return this.nbMicIdn;
	}

	public void setNbMicIdn(BigDecimal nbMicIdn) {
		this.nbMicIdn = nbMicIdn;
	}

	public TbMicEstadomic getTbMicEstadomic() {
		return this.tbMicEstadomic;
	}

	public void setTbMicEstadomic(TbMicEstadomic tbMicEstadomic) {
		this.tbMicEstadomic = tbMicEstadomic;
	}

	public TbMicNucleoacademico getTbMicNucleoacademico() {
		return this.tbMicNucleoacademico;
	}

	public void setTbMicNucleoacademico(
			TbMicNucleoacademico tbMicNucleoacademico) {
		this.tbMicNucleoacademico = tbMicNucleoacademico;
	}

	public TbAdmSemestrexcurso getTbAdmSemestrexcurso() {
		return this.tbAdmSemestrexcurso;
	}

	public void setTbAdmSemestrexcurso(TbAdmSemestrexcurso tbAdmSemestrexcurso) {
		this.tbAdmSemestrexcurso = tbAdmSemestrexcurso;
	}

	public TbMicEvaluacion getTbMicEvaluacion() {
		return this.tbMicEvaluacion;
	}

	public void setTbMicEvaluacion(TbMicEvaluacion tbMicEvaluacion) {
		this.tbMicEvaluacion = tbMicEvaluacion;
	}

	public TbMicActa getTbMicActa() {
		return this.tbMicActa;
	}

	public void setTbMicActa(TbMicActa tbMicActa) {
		this.tbMicActa = tbMicActa;
	}

	public TbMicUnidades getTbMicUnidades() {
		return this.tbMicUnidades;
	}

	public void setTbMicUnidades(TbMicUnidades tbMicUnidades) {
		this.tbMicUnidades = tbMicUnidades;
	}

	public String getVrAdtusuario() {
		return this.vrAdtusuario;
	}

	public void setVrAdtusuario(String vrAdtusuario) {
		this.vrAdtusuario = vrAdtusuario;
	}

	public Date getDtAdtfecha() {
		return this.dtAdtfecha;
	}

	public void setDtAdtfecha(Date dtAdtfecha) {
		this.dtAdtfecha = dtAdtfecha;
	}

	public String getVrMicNombre() {
		return this.vrMicNombre;
	}

	public void setVrMicNombre(String vrMicNombre) {
		this.vrMicNombre = vrMicNombre;
	}

	public String getVrMicValidable() {
		return this.vrMicValidable;
	}

	public void setVrMicValidable(String vrMicValidable) {
		this.vrMicValidable = vrMicValidable;
	}

	public Byte getNbMicHorasteoricasemanales() {
		return this.nbMicHorasteoricasemanales;
	}

	public void setNbMicHorasteoricasemanales(Byte nbMicHorasteoricasemanales) {
		this.nbMicHorasteoricasemanales = nbMicHorasteoricasemanales;
	}

	public Short getNbMicHorasterosem() {
		return this.nbMicHorasterosem;
	}

	public void setNbMicHorasterosem(Short nbMicHorasterosem) {
		this.nbMicHorasterosem = nbMicHorasterosem;
	}

	public Byte getNbMicNumerocreditos() {
		return this.nbMicNumerocreditos;
	}

	public void setNbMicNumerocreditos(Byte nbMicNumerocreditos) {
		this.nbMicNumerocreditos = nbMicNumerocreditos;
	}

	public Short getNbHorasclasexsemestre() {
		return this.nbHorasclasexsemestre;
	}

	public void setNbHorasclasexsemestre(Short nbHorasclasexsemestre) {
		this.nbHorasclasexsemestre = nbHorasclasexsemestre;
	}

	public String getVrMicCampodeformacion() {
		return this.vrMicCampodeformacion;
	}

	public void setVrMicCampodeformacion(String vrMicCampodeformacion) {
		this.vrMicCampodeformacion = vrMicCampodeformacion;
	}

	public String getVrMicHabilitable() {
		return this.vrMicHabilitable;
	}

	public void setVrMicHabilitable(String vrMicHabilitable) {
		this.vrMicHabilitable = vrMicHabilitable;
	}

	public String getVrMicClasificable() {
		return this.vrMicClasificable;
	}

	public void setVrMicClasificable(String vrMicClasificable) {
		this.vrMicClasificable = vrMicClasificable;
	}

	public String getVrMicRequisitos() {
		return this.vrMicRequisitos;
	}

	public void setVrMicRequisitos(String vrMicRequisitos) {
		this.vrMicRequisitos = vrMicRequisitos;
	}

	public String getVrMicCorrequisito() {
		return this.vrMicCorrequisito;
	}

	public void setVrMicCorrequisito(String vrMicCorrequisito) {
		this.vrMicCorrequisito = vrMicCorrequisito;
	}

	public byte getNbMicProgram() {
		return this.nbMicProgram;
	}

	public void setNbMicProgram(byte nbMicProgram) {
		this.nbMicProgram = nbMicProgram;
	}

	public String getVrMicProposito() {
		return this.vrMicProposito;
	}

	public void setVrMicProposito(String vrMicProposito) {
		this.vrMicProposito = vrMicProposito;
	}

	public String getVrMicJustificacion() {
		return this.vrMicJustificacion;
	}

	public void setVrMicJustificacion(String vrMicJustificacion) {
		this.vrMicJustificacion = vrMicJustificacion;
	}

	public String getVrMicObjetivogeneral() {
		return this.vrMicObjetivogeneral;
	}

	public void setVrMicObjetivogeneral(String vrMicObjetivogeneral) {
		this.vrMicObjetivogeneral = vrMicObjetivogeneral;
	}

	public String getVrMicObjetivosespecificos() {
		return this.vrMicObjetivosespecificos;
	}

	public void setVrMicObjetivosespecificos(String vrMicObjetivosespecificos) {
		this.vrMicObjetivosespecificos = vrMicObjetivosespecificos;
	}

	public String getVrMicContenidoresumido() {
		return this.vrMicContenidoresumido;
	}

	public void setVrMicContenidoresumido(String vrMicContenidoresumido) {
		this.vrMicContenidoresumido = vrMicContenidoresumido;
	}

	public Byte getNbMicEstado() {
		return this.nbMicEstado;
	}

	public void setNbMicEstado(Byte nbMicEstado) {
		this.nbMicEstado = nbMicEstado;
	}

	public String getVrMicBibliografia() {
		return this.vrMicBibliografia;
	}

	public void setVrMicBibliografia(String vrMicBibliografia) {
		this.vrMicBibliografia = vrMicBibliografia;
	}

}
