// default package
// Generated 10-may-2014 11:58:30 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TbMicNucleoacademico generated by hbm2java
 */
public class TbMicNucleoacademico implements java.io.Serializable {

	private long nbNacIdn;
	private String vrAdtusuario;
	private Date dtAdtfecha;
	private String vrNacNombrenucleo;
	private Set tbMicMicrocurriculos = new HashSet(0);

	public TbMicNucleoacademico() {
	}

	public TbMicNucleoacademico(long nbNacIdn) {
		this.nbNacIdn = nbNacIdn;
	}

	public TbMicNucleoacademico(long nbNacIdn, String vrAdtusuario,
			Date dtAdtfecha, String vrNacNombrenucleo, Set tbMicMicrocurriculos) {
		this.nbNacIdn = nbNacIdn;
		this.vrAdtusuario = vrAdtusuario;
		this.dtAdtfecha = dtAdtfecha;
		this.vrNacNombrenucleo = vrNacNombrenucleo;
		this.tbMicMicrocurriculos = tbMicMicrocurriculos;
	}

	public long getNbNacIdn() {
		return this.nbNacIdn;
	}

	public void setNbNacIdn(long nbNacIdn) {
		this.nbNacIdn = nbNacIdn;
	}

	public String getVrAdtusuario() {
		return this.vrAdtusuario;
	}

	public void setVrAdtusuario(String vrAdtusuario) {
		this.vrAdtusuario = vrAdtusuario;
	}

	public Date getDtAdtfecha() {
		return this.dtAdtfecha;
	}

	public void setDtAdtfecha(Date dtAdtfecha) {
		this.dtAdtfecha = dtAdtfecha;
	}

	public String getVrNacNombrenucleo() {
		return this.vrNacNombrenucleo;
	}

	public void setVrNacNombrenucleo(String vrNacNombrenucleo) {
		this.vrNacNombrenucleo = vrNacNombrenucleo;
	}

	public Set getTbMicMicrocurriculos() {
		return this.tbMicMicrocurriculos;
	}

	public void setTbMicMicrocurriculos(Set tbMicMicrocurriculos) {
		this.tbMicMicrocurriculos = tbMicMicrocurriculos;
	}

}
