// default package
// Generated 10-may-2014 11:58:30 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TbMicUnidades generated by hbm2java
 */
public class TbMicUnidades implements java.io.Serializable {

	private long nbUniIdn;
	private String vrAdtusuario;
	private Date dtAdtfecha;
	private String vrUniNombreuni;
	private Set tbMicMicrocurriculos = new HashSet(0);

	public TbMicUnidades() {
	}

	public TbMicUnidades(long nbUniIdn) {
		this.nbUniIdn = nbUniIdn;
	}

	public TbMicUnidades(long nbUniIdn, String vrAdtusuario, Date dtAdtfecha,
			String vrUniNombreuni, Set tbMicMicrocurriculos) {
		this.nbUniIdn = nbUniIdn;
		this.vrAdtusuario = vrAdtusuario;
		this.dtAdtfecha = dtAdtfecha;
		this.vrUniNombreuni = vrUniNombreuni;
		this.tbMicMicrocurriculos = tbMicMicrocurriculos;
	}

	public long getNbUniIdn() {
		return this.nbUniIdn;
	}

	public void setNbUniIdn(long nbUniIdn) {
		this.nbUniIdn = nbUniIdn;
	}

	public String getVrAdtusuario() {
		return this.vrAdtusuario;
	}

	public void setVrAdtusuario(String vrAdtusuario) {
		this.vrAdtusuario = vrAdtusuario;
	}

	public Date getDtAdtfecha() {
		return this.dtAdtfecha;
	}

	public void setDtAdtfecha(Date dtAdtfecha) {
		this.dtAdtfecha = dtAdtfecha;
	}

	public String getVrUniNombreuni() {
		return this.vrUniNombreuni;
	}

	public void setVrUniNombreuni(String vrUniNombreuni) {
		this.vrUniNombreuni = vrUniNombreuni;
	}

	public Set getTbMicMicrocurriculos() {
		return this.tbMicMicrocurriculos;
	}

	public void setTbMicMicrocurriculos(Set tbMicMicrocurriculos) {
		this.tbMicMicrocurriculos = tbMicMicrocurriculos;
	}

}
