package com.proint1.udea.administracion.entidades.dependencias;
// default package
// Generated 10-may-2014 11:58:30 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import com.proint1.udea.administracion.entidades.configuracion.Pais;

/**
 * TbAdmUniversidades generated by hbm2java
 */
public class Universidad implements java.io.Serializable {

	private long nbIdm;
	private Pais tbAdmPaises;
	private String vrNombre;
	private Date dtAdtfecha;
	private String vrAdtusuario;

	public Universidad() {
	}

	public Universidad(long nbIdm, Pais tbAdmPaises,
			String vrNombre, Date dtAdtfecha, String vrAdtusuario) {
		this.nbIdm = nbIdm;
		this.tbAdmPaises = tbAdmPaises;
		this.vrNombre = vrNombre;
		this.dtAdtfecha = dtAdtfecha;
		this.vrAdtusuario = vrAdtusuario;
	}

	public long getNbIdm() {
		return this.nbIdm;
	}

	public void setNbIdm(long nbIdm) {
		this.nbIdm = nbIdm;
	}

	public Pais getTbAdmPaises() {
		return this.tbAdmPaises;
	}

	public void setTbAdmPaises(Pais tbAdmPaises) {
		this.tbAdmPaises = tbAdmPaises;
	}

	public String getVrNombre() {
		return this.vrNombre;
	}

	public void setVrNombre(String vrNombre) {
		this.vrNombre = vrNombre;
	}

	public Date getDtAdtfecha() {
		return this.dtAdtfecha;
	}

	public void setDtAdtfecha(Date dtAdtfecha) {
		this.dtAdtfecha = dtAdtfecha;
	}

	public String getVrAdtusuario() {
		return this.vrAdtusuario;
	}

	public void setVrAdtusuario(String vrAdtusuario) {
		this.vrAdtusuario = vrAdtusuario;
	}

}
