package com.proint1.udea.administracion.entidades.seguridad;
// default package
// Generated 10-may-2014 11:58:30 by Hibernate Tools 3.4.0.CR1

/**
 * TbAdmPermisosxrol generated by hbm2java
 */
public class PermisoRol implements java.io.Serializable {

	private PermisoRolId id;
	private Recurso tbAdmRecurso;
	private Rol tbAdmRol;

	public PermisoRol() {
	}

	public PermisoRol(PermisoRolId id, Recurso tbAdmRecurso,
			Rol tbAdmRol) {
		this.id = id;
		this.tbAdmRecurso = tbAdmRecurso;
		this.tbAdmRol = tbAdmRol;
	}

	public PermisoRolId getId() {
		return this.id;
	}

	public void setId(PermisoRolId id) {
		this.id = id;
	}

	public Recurso getTbAdmRecurso() {
		return this.tbAdmRecurso;
	}

	public void setTbAdmRecurso(Recurso tbAdmRecurso) {
		this.tbAdmRecurso = tbAdmRecurso;
	}

	public Rol getTbAdmRol() {
		return this.tbAdmRol;
	}

	public void setTbAdmRol(Rol tbAdmRol) {
		this.tbAdmRol = tbAdmRol;
	}

}
