package com.proint1.udea.administracion.entidades.seguridad;
// default package
// Generated 10-may-2014 11:58:30 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * TbAdmRecurso generated by hbm2java
 */
public class Recurso implements java.io.Serializable {

	private long nbRecIdn;
	private Recurso tbAdmRecurso;
	private String vrRecNombre;
	private String vrRecTipo;
	private Set tbAdmPermisosxrols = new HashSet(0);
	private Set tbAdmRecursos = new HashSet(0);

	public Recurso() {
	}

	public Recurso(long nbRecIdn, Recurso tbAdmRecurso,
			String vrRecNombre, String vrRecTipo) {
		this.nbRecIdn = nbRecIdn;
		this.tbAdmRecurso = tbAdmRecurso;
		this.vrRecNombre = vrRecNombre;
		this.vrRecTipo = vrRecTipo;
	}

	public Recurso(long nbRecIdn, Recurso tbAdmRecurso,
			String vrRecNombre, String vrRecTipo, Set tbAdmPermisosxrols,
			Set tbAdmRecursos) {
		this.nbRecIdn = nbRecIdn;
		this.tbAdmRecurso = tbAdmRecurso;
		this.vrRecNombre = vrRecNombre;
		this.vrRecTipo = vrRecTipo;
		this.tbAdmPermisosxrols = tbAdmPermisosxrols;
		this.tbAdmRecursos = tbAdmRecursos;
	}

	public long getNbRecIdn() {
		return this.nbRecIdn;
	}

	public void setNbRecIdn(long nbRecIdn) {
		this.nbRecIdn = nbRecIdn;
	}

	public Recurso getTbAdmRecurso() {
		return this.tbAdmRecurso;
	}

	public void setTbAdmRecurso(Recurso tbAdmRecurso) {
		this.tbAdmRecurso = tbAdmRecurso;
	}

	public String getVrRecNombre() {
		return this.vrRecNombre;
	}

	public void setVrRecNombre(String vrRecNombre) {
		this.vrRecNombre = vrRecNombre;
	}

	public String getVrRecTipo() {
		return this.vrRecTipo;
	}

	public void setVrRecTipo(String vrRecTipo) {
		this.vrRecTipo = vrRecTipo;
	}

	public Set getTbAdmPermisosxrols() {
		return this.tbAdmPermisosxrols;
	}

	public void setTbAdmPermisosxrols(Set tbAdmPermisosxrols) {
		this.tbAdmPermisosxrols = tbAdmPermisosxrols;
	}

	public Set getTbAdmRecursos() {
		return this.tbAdmRecursos;
	}

	public void setTbAdmRecursos(Set tbAdmRecursos) {
		this.tbAdmRecursos = tbAdmRecursos;
	}

}
