package com.proint1.udea.administracion.entidades.seguridad;
// default package
// Generated 10-may-2014 11:58:30 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * TbAdmRol generated by hbm2java
 */
public class Rol implements java.io.Serializable {

	private BigDecimal nbRolIdn;
	private String vrRolNombre;
	private Set tbAdmUsuarioxrols = new HashSet(0);
	private Set tbAdmPermisosxrols = new HashSet(0);

	public Rol() {
	}

	public Rol(BigDecimal nbRolIdn, String vrRolNombre) {
		this.nbRolIdn = nbRolIdn;
		this.vrRolNombre = vrRolNombre;
	}

	public Rol(BigDecimal nbRolIdn, String vrRolNombre,
			Set tbAdmUsuarioxrols, Set tbAdmPermisosxrols) {
		this.nbRolIdn = nbRolIdn;
		this.vrRolNombre = vrRolNombre;
		this.tbAdmUsuarioxrols = tbAdmUsuarioxrols;
		this.tbAdmPermisosxrols = tbAdmPermisosxrols;
	}

	public BigDecimal getNbRolIdn() {
		return this.nbRolIdn;
	}

	public void setNbRolIdn(BigDecimal nbRolIdn) {
		this.nbRolIdn = nbRolIdn;
	}

	public String getVrRolNombre() {
		return this.vrRolNombre;
	}

	public void setVrRolNombre(String vrRolNombre) {
		this.vrRolNombre = vrRolNombre;
	}

	public Set getTbAdmUsuarioxrols() {
		return this.tbAdmUsuarioxrols;
	}

	public void setTbAdmUsuarioxrols(Set tbAdmUsuarioxrols) {
		this.tbAdmUsuarioxrols = tbAdmUsuarioxrols;
	}

	public Set getTbAdmPermisosxrols() {
		return this.tbAdmPermisosxrols;
	}

	public void setTbAdmPermisosxrols(Set tbAdmPermisosxrols) {
		this.tbAdmPermisosxrols = tbAdmPermisosxrols;
	}

}
