package com.proint1.udea.administracion.entidades.seguridad;

// default package
// Generated 10-may-2014 11:58:30 by Hibernate Tools 3.4.0.CR1

/**
 * TbAdmUsuarioxrol generated by hbm2java
 */
public class UsuarioRol implements java.io.Serializable {

	private long nbUxrIdn;
	private Usuario tbAdmUsuario;
	private Rol tbAdmRol;

	public UsuarioRol() {
	}

	public UsuarioRol(long nbUxrIdn, Usuario tbAdmUsuario,
			Rol tbAdmRol) {
		this.nbUxrIdn = nbUxrIdn;
		this.tbAdmUsuario = tbAdmUsuario;
		this.tbAdmRol = tbAdmRol;
	}

	public long getNbUxrIdn() {
		return this.nbUxrIdn;
	}

	public void setNbUxrIdn(long nbUxrIdn) {
		this.nbUxrIdn = nbUxrIdn;
	}

	public Usuario getTbAdmUsuario() {
		return this.tbAdmUsuario;
	}

	public void setTbAdmUsuario(Usuario tbAdmUsuario) {
		this.tbAdmUsuario = tbAdmUsuario;
	}

	public Rol getTbAdmRol() {
		return this.tbAdmRol;
	}

	public void setTbAdmRol(Rol tbAdmRol) {
		this.tbAdmRol = tbAdmRol;
	}

}
