package com.proint1.udea.administracion.entidades.academico;

import com.proint1.udea.administracion.entidades.dependencias.DependenciaAcademica;
// default package
// Generated 10-may-2014 11:58:30 by Hibernate Tools 3.4.0.CR1
import com.proint1.udea.administracion.entidades.terceros.Estudiante;

/**
 * TbAdmMatricula generated by hbm2java
 */
public class Matricula implements java.io.Serializable {

	private long nbMatIdn;
	private Estudiante tbAdmEstudiante;
	private DependenciaAcademica tbAdmDependenciaAcademica;
	private Semestre tbAdmSemestre;
	private Grupo tbAdmGrupo;

	public Matricula() {
	}

	public Matricula(long nbMatIdn, Estudiante tbAdmEstudiante,
			DependenciaAcademica tbAdmDependenciaAcademica,
			Semestre tbAdmSemestre, Grupo tbAdmGrupo) {
		this.nbMatIdn = nbMatIdn;
		this.tbAdmEstudiante = tbAdmEstudiante;
		this.tbAdmDependenciaAcademica = tbAdmDependenciaAcademica;
		this.tbAdmSemestre = tbAdmSemestre;
		this.tbAdmGrupo = tbAdmGrupo;
	}

	public long getNbMatIdn() {
		return this.nbMatIdn;
	}

	public void setNbMatIdn(long nbMatIdn) {
		this.nbMatIdn = nbMatIdn;
	}

	public Estudiante getTbAdmEstudiante() {
		return this.tbAdmEstudiante;
	}

	public void setTbAdmEstudiante(Estudiante tbAdmEstudiante) {
		this.tbAdmEstudiante = tbAdmEstudiante;
	}

	public DependenciaAcademica getTbAdmDependenciaAcademica() {
		return this.tbAdmDependenciaAcademica;
	}

	public void setTbAdmDependenciaAcademica(
			DependenciaAcademica tbAdmDependenciaAcademica) {
		this.tbAdmDependenciaAcademica = tbAdmDependenciaAcademica;
	}

	public Semestre getTbAdmSemestre() {
		return this.tbAdmSemestre;
	}

	public void setTbAdmSemestre(Semestre tbAdmSemestre) {
		this.tbAdmSemestre = tbAdmSemestre;
	}

	public Grupo getTbAdmGrupo() {
		return this.tbAdmGrupo;
	}

	public void setTbAdmGrupo(Grupo tbAdmGrupo) {
		this.tbAdmGrupo = tbAdmGrupo;
	}

}
