package com.proint1.udea.administracion.entidades.academico;
// default package
// Generated 10-may-2014 11:58:30 by Hibernate Tools 3.4.0.CR1



/**
 * TbAdmSemestrexcurso generated by hbm2java
 */
public class SemestreCurso implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3056638391618518130L;
	
	private long idn;
	private Curso curso;
	private Semestre semestre;
	private ModalidadCurso modalidadCurso;
	private long cursoIDN;
	private long semestreIDN;
	private String modalidadCursoIDN;
	private Double totalTiempo;
	/**
	 * 
	 */
	public SemestreCurso() {
		super();
		// TODO Auto-generated constructor stub
	}
	
	
	
	
	
	/**
	 * @param curso
	 * @param semestre
	 * @param grupo
	 * @param modalidadCurso
	 * @param totalTiempo
	 */
	public SemestreCurso(Curso curso, Semestre semestre, 
			ModalidadCurso modalidadCurso, Double totalTiempo) {
		super();
		this.curso = curso;
		this.semestre = semestre;
		this.modalidadCurso = modalidadCurso;
		this.totalTiempo = totalTiempo;
	}





	/**
	 * @param cursoIDN
	 * @param semestreIDN
	 * @param grupoIDN
	 * @param modalidadCursoIDN
	 * @param totalTiempo
	 */
	public SemestreCurso(long cursoIDN, long semestreIDN, 
			String modalidadCursoIDN, Double totalTiempo) {
		super();
		this.cursoIDN = cursoIDN;
		this.semestreIDN = semestreIDN;
		this.modalidadCursoIDN = modalidadCursoIDN;
		this.totalTiempo = totalTiempo;
	}





	/**
	 * @param cursoIDN
	 * @param semestreIDN
	 * @param grupoIDN
	 * @param modalidadCursoIDN
	 */
	public SemestreCurso(long cursoIDN, long semestreIDN,String modalidadCursoIDN) {
		super();
		this.cursoIDN = cursoIDN;
		this.semestreIDN = semestreIDN;
		this.modalidadCursoIDN = modalidadCursoIDN;
	}





	/**
	 * @return the idn
	 */
	public long getIdn() {
		return idn;
	}
	/**
	 * @param idn the idn to set
	 */
	public void setIdn(long idn) {
		this.idn = idn;
	}
	/**
	 * @return the curso
	 */
	public Curso getCurso() {
		return curso;
	}
	/**
	 * @param curso the curso to set
	 */
	public void setCurso(Curso curso) {
		this.curso = curso;
	}
	/**
	 * @return the semestre
	 */
	public Semestre getSemestre() {
		return semestre;
	}
	/**
	 * @param semestre the semestre to set
	 */
	public void setSemestre(Semestre semestre) {
		this.semestre = semestre;
	}
	
	
	/**
	 * @return the modalidadCurso
	 */
	public ModalidadCurso getModalidadCurso() {
		return modalidadCurso;
	}
	/**
	 * @param modalidadCurso the modalidadCurso to set
	 */
	public void setModalidadCurso(ModalidadCurso modalidadCurso) {
		this.modalidadCurso = modalidadCurso;
	}
	/**
	 * @return the cursoIDN
	 */
	public long getCursoIDN() {
		return cursoIDN;
	}
	/**
	 * @param cursoIDN the cursoIDN to set
	 */
	public void setCursoIDN(long cursoIDN) {
		this.cursoIDN = cursoIDN;
	}
	/**
	 * @return the semestreIDN
	 */
	public long getSemestreIDN() {
		return semestreIDN;
	}
	/**
	 * @param semestreIDN the semestreIDN to set
	 */
	public void setSemestreIDN(long semestreIDN) {
		this.semestreIDN = semestreIDN;
	}
	
	/**
	 * @return the modalidadCursoIDN
	 */
	public String getModalidadCursoIDN() {
		return modalidadCursoIDN;
	}
	/**
	 * @param modalidadCursoIDN the modalidadCursoIDN to set
	 */
	public void setModalidadCursoIDN(String modalidadCursoIDN) {
		this.modalidadCursoIDN = modalidadCursoIDN;
	}
	/**
	 * @return the totalTiempo
	 */
	public Double getTotalTiempo() {
		return totalTiempo;
	}
	/**
	 * @param totalTiempo the totalTiempo to set
	 */
	public void setTotalTiempo(Double totalTiempo) {
		this.totalTiempo = totalTiempo;
	}
	/**
	 * @return the serialversionuid
	 */
	public static long getSerialversionuid() {
		return serialVersionUID;
	}	
}
