package com.proint1.udea.administracion.entidades.configuracion;
// default package
// Generated 10-may-2014 11:58:30 by Hibernate Tools 3.4.0.CR1

/**
 * TbAdmPropiedadesId generated by hbm2java
 */
public class ParametroId implements java.io.Serializable {

	private long nbPrpIdn;
	private String vrPrpValor;

	public ParametroId() {
	}

	public ParametroId(long nbPrpIdn, String vrPrpValor) {
		this.nbPrpIdn = nbPrpIdn;
		this.vrPrpValor = vrPrpValor;
	}

	public long getNbPrpIdn() {
		return this.nbPrpIdn;
	}

	public void setNbPrpIdn(long nbPrpIdn) {
		this.nbPrpIdn = nbPrpIdn;
	}

	public String getVrPrpValor() {
		return this.vrPrpValor;
	}

	public void setVrPrpValor(String vrPrpValor) {
		this.vrPrpValor = vrPrpValor;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ParametroId))
			return false;
		ParametroId castOther = (ParametroId) other;

		return (this.getNbPrpIdn() == castOther.getNbPrpIdn())
				&& ((this.getVrPrpValor() == castOther.getVrPrpValor()) || (this
						.getVrPrpValor() != null
						&& castOther.getVrPrpValor() != null && this
						.getVrPrpValor().equals(castOther.getVrPrpValor())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getNbPrpIdn();
		result = 37
				* result
				+ (getVrPrpValor() == null ? 0 : this.getVrPrpValor()
						.hashCode());
		return result;
	}

}
