package com.proint1.udea.administracion.entidades.configuracion;

import com.proint1.udea.administracion.entidades.dependencias.DependenciaAcademica;
// default package
// Generated 10-may-2014 11:58:30 by Hibernate Tools 3.4.0.CR1

/**
 * TbAdmPropiedades generated by hbm2java
 */
public class Parametro implements java.io.Serializable {

	private ParametroId id;
	private DependenciaAcademica tbAdmDependenciaAcademica;
	private String vrPrpCodigo;

	public Parametro() {
	}

	public Parametro(ParametroId id,
			DependenciaAcademica tbAdmDependenciaAcademica,
			String vrPrpCodigo) {
		this.id = id;
		this.tbAdmDependenciaAcademica = tbAdmDependenciaAcademica;
		this.vrPrpCodigo = vrPrpCodigo;
	}

	public ParametroId getId() {
		return this.id;
	}

	public void setId(ParametroId id) {
		this.id = id;
	}

	public DependenciaAcademica getTbAdmDependenciaAcademica() {
		return this.tbAdmDependenciaAcademica;
	}

	public void setTbAdmDependenciaAcademica(
			DependenciaAcademica tbAdmDependenciaAcademica) {
		this.tbAdmDependenciaAcademica = tbAdmDependenciaAcademica;
	}

	public String getVrPrpCodigo() {
		return this.vrPrpCodigo;
	}

	public void setVrPrpCodigo(String vrPrpCodigo) {
		this.vrPrpCodigo = vrPrpCodigo;
	}

}
