package com.proint1.udea.administracion.entidades.configuracion;
// default package
// Generated 10-may-2014 11:58:30 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

import com.proint1.udea.administracion.entidades.dependencias.DependenciaAcademica;

/**
 * TbAdmTareasProgramadas generated by hbm2java
 */
public class TareaProgramada implements java.io.Serializable {

	private BigDecimal nbTprIdn;
	private DependenciaAcademica tbAdmDependenciaAcademica;
	private String vrTprNombre;
	private String vrTprManager;
	private char nbTprActiva;
	private String vrAdtusuario;
	private Date dtAdtfecha;

	public TareaProgramada() {
	}

	public TareaProgramada(BigDecimal nbTprIdn,
			DependenciaAcademica tbAdmDependenciaAcademica,
			String vrTprNombre, String vrTprManager, char nbTprActiva) {
		this.nbTprIdn = nbTprIdn;
		this.tbAdmDependenciaAcademica = tbAdmDependenciaAcademica;
		this.vrTprNombre = vrTprNombre;
		this.vrTprManager = vrTprManager;
		this.nbTprActiva = nbTprActiva;
	}

	public TareaProgramada(BigDecimal nbTprIdn,
			DependenciaAcademica tbAdmDependenciaAcademica,
			String vrTprNombre, String vrTprManager, char nbTprActiva,
			String vrAdtusuario, Date dtAdtfecha) {
		this.nbTprIdn = nbTprIdn;
		this.tbAdmDependenciaAcademica = tbAdmDependenciaAcademica;
		this.vrTprNombre = vrTprNombre;
		this.vrTprManager = vrTprManager;
		this.nbTprActiva = nbTprActiva;
		this.vrAdtusuario = vrAdtusuario;
		this.dtAdtfecha = dtAdtfecha;
	}

	public BigDecimal getNbTprIdn() {
		return this.nbTprIdn;
	}

	public void setNbTprIdn(BigDecimal nbTprIdn) {
		this.nbTprIdn = nbTprIdn;
	}

	public DependenciaAcademica getTbAdmDependenciaAcademica() {
		return this.tbAdmDependenciaAcademica;
	}

	public void setTbAdmDependenciaAcademica(
			DependenciaAcademica tbAdmDependenciaAcademica) {
		this.tbAdmDependenciaAcademica = tbAdmDependenciaAcademica;
	}

	public String getVrTprNombre() {
		return this.vrTprNombre;
	}

	public void setVrTprNombre(String vrTprNombre) {
		this.vrTprNombre = vrTprNombre;
	}

	public String getVrTprManager() {
		return this.vrTprManager;
	}

	public void setVrTprManager(String vrTprManager) {
		this.vrTprManager = vrTprManager;
	}

	public char getNbTprActiva() {
		return this.nbTprActiva;
	}

	public void setNbTprActiva(char nbTprActiva) {
		this.nbTprActiva = nbTprActiva;
	}

	public String getVrAdtusuario() {
		return this.vrAdtusuario;
	}

	public void setVrAdtusuario(String vrAdtusuario) {
		this.vrAdtusuario = vrAdtusuario;
	}

	public Date getDtAdtfecha() {
		return this.dtAdtfecha;
	}

	public void setDtAdtfecha(Date dtAdtfecha) {
		this.dtAdtfecha = dtAdtfecha;
	}

}
