-- Generado por Oracle SQL Developer Data Modeler 4.0.1.836
--   en:        2014-05-09 23:50:34 COT
--   sitio:      Oracle Database 11g
--   tipo:      Oracle Database 11g




DROP TABLE TB_ACT_DOCENTEXGRUPO CASCADE CONSTRAINTS ;

DROP TABLE TB_ACT_REPORTEACTIVIDAD CASCADE CONSTRAINTS ;

DROP TABLE TB_ACT_TIPO_ACTIVIDAD CASCADE CONSTRAINTS ;

DROP TABLE TB_ADM_CURSO CASCADE CONSTRAINTS ;

DROP TABLE TB_ADM_DEPENDENCIA_ACADEMICA CASCADE CONSTRAINTS ;

DROP TABLE TB_ADM_DOCENTE CASCADE CONSTRAINTS ;

DROP TABLE TB_ADM_DOCENTESXDEPENDENCIA CASCADE CONSTRAINTS ;

DROP TABLE TB_ADM_ESTADO_SEMESTRE CASCADE CONSTRAINTS ;

DROP TABLE TB_ADM_ESTUDIANTE CASCADE CONSTRAINTS ;

DROP TABLE TB_ADM_GRUPO CASCADE CONSTRAINTS ;

DROP TABLE TB_ADM_MATRICULA CASCADE CONSTRAINTS ;

DROP TABLE TB_ADM_MODALIDAD_CURSO CASCADE CONSTRAINTS ;

DROP TABLE TB_ADM_PAISES CASCADE CONSTRAINTS ;

DROP TABLE TB_ADM_PERMISOSXROL CASCADE CONSTRAINTS ;

DROP TABLE TB_ADM_PERSONA CASCADE CONSTRAINTS ;

DROP TABLE TB_ADM_PROPIEDADES CASCADE CONSTRAINTS ;

DROP TABLE TB_ADM_RECURSO CASCADE CONSTRAINTS ;

DROP TABLE TB_ADM_ROL CASCADE CONSTRAINTS ;

DROP TABLE TB_ADM_SEMESTRE CASCADE CONSTRAINTS ;

DROP TABLE TB_ADM_SEMESTREXCURSO CASCADE CONSTRAINTS ;

DROP TABLE TB_ADM_TAREAS_PROGRAMADAS CASCADE CONSTRAINTS ;

DROP TABLE TB_ADM_TIPOIDENTIFICACION CASCADE CONSTRAINTS ;

DROP TABLE TB_ADM_TIPO_DEPENDENCIA CASCADE CONSTRAINTS ;

DROP TABLE TB_ADM_UNIDAD_ACADEMICA CASCADE CONSTRAINTS ;

DROP TABLE TB_ADM_UNIVERSIDADES CASCADE CONSTRAINTS ;

DROP TABLE TB_ADM_USUARIO CASCADE CONSTRAINTS ;

DROP TABLE TB_ADM_USUARIOXROL CASCADE CONSTRAINTS ;

DROP TABLE TB_MIC_ACTA CASCADE CONSTRAINTS ;

DROP TABLE TB_MIC_CURSOSXPENSUM CASCADE CONSTRAINTS ;

DROP TABLE TB_MIC_ESTADOMIC CASCADE CONSTRAINTS ;

DROP TABLE TB_MIC_EVALUACION CASCADE CONSTRAINTS ;

DROP TABLE TB_MIC_MICROCURRICULO CASCADE CONSTRAINTS ;

DROP TABLE TB_MIC_NUCLEOACADEMICO CASCADE CONSTRAINTS ;

DROP TABLE TB_MIC_UNIDADES CASCADE CONSTRAINTS ;

DROP TABLE TB_MIC_VERSIONPENSUM CASCADE CONSTRAINTS ;

DROP TABLE TB_PRD_AUTOR CASCADE CONSTRAINTS ;

DROP TABLE TB_PRD_AUTORESXPRODUCCION CASCADE CONSTRAINTS ;

DROP TABLE TB_PRD_CAMPOS CASCADE CONSTRAINTS ;

DROP TABLE TB_PRD_DETALLEPRODUCIONES CASCADE CONSTRAINTS ;

DROP TABLE TB_PRD_GRUPOINVESTIGACION CASCADE CONSTRAINTS ;

DROP TABLE TB_PRD_MIEMBROSXGRUPO CASCADE CONSTRAINTS ;

DROP TABLE TB_PRD_PRODUCCION CASCADE CONSTRAINTS ;

DROP TABLE TB_PRD_TIPOPRODUCCION CASCADE CONSTRAINTS ;

DROP TABLE TB_PRD_TIPOPRODUCIONESXCAMPO CASCADE CONSTRAINTS ;

CREATE TABLE TB_ACT_DOCENTEXGRUPO
  (
    NB_DOG_IDN         NUMBER (10) NOT NULL ,
    NB_DOG_TIEMPOTOTAL NUMBER (14,4) ,
    NB_DOC_IDN         NUMBER (10) NOT NULL ,
    NB_GPO_IDN         NUMBER (10) NOT NULL ,
    VR_ADTUSUARIO      VARCHAR2 (32 BYTE) ,
    DT_ADTFECHA        DATE
  ) ;
ALTER TABLE TB_ACT_DOCENTEXGRUPO ADD CONSTRAINT DOCENTEXGRUPO_PK PRIMARY KEY ( NB_DOG_IDN ) ;

CREATE TABLE TB_ACT_REPORTEACTIVIDAD
  (
    NB_RAC_IDN         NUMBER (10) NOT NULL ,
    NB_TAC_IDN         NUMBER (10) NOT NULL ,
    NB_DOG_IDN         NUMBER (10) NOT NULL ,
    DT_RAC_FECHA       DATE NOT NULL ,
    VR_RAC_DESCRIPCION VARCHAR2 (500 BYTE) ,
    NB_RAC_TIEMPO      NUMBER (14,4) NOT NULL ,
    VR_ADTUSUARIO      VARCHAR2 (32 BYTE) ,
    DT_ADTFECHA        DATE
  ) ;
ALTER TABLE TB_ACT_REPORTEACTIVIDAD ADD CONSTRAINT REPORTEACTIVIDAD_PK PRIMARY KEY ( NB_RAC_IDN ) ;

CREATE TABLE TB_ACT_TIPO_ACTIVIDAD
  (
    NB_TAC_IDN         NUMBER (10) NOT NULL ,
    VR_TAC_NOMBRE      VARCHAR2 (50 BYTE) NOT NULL ,
    VR_TAC_DESCRIPCION VARCHAR2 (255 BYTE) NOT NULL
  ) ;
ALTER TABLE TB_ACT_TIPO_ACTIVIDAD ADD CONSTRAINT ACTIVIDAD_PK PRIMARY KEY ( NB_TAC_IDN ) ;

CREATE TABLE TB_ADM_CURSO
  (
    NB_CUR_IDN    NUMBER (10) NOT NULL ,
    VR_CUR_ID     VARCHAR2 (10 BYTE) NOT NULL ,
    VR_CUR_NOMBRE VARCHAR2 (50 BYTE) NOT NULL ,
    VR_ADTUSUARIO VARCHAR2 (32 BYTE) ,
    DT_ADTFECHA   DATE ,
    BN_DEP_IDN    NUMBER (10) NOT NULL
  ) ;
ALTER TABLE TB_ADM_CURSO ADD CONSTRAINT CURSO_PK PRIMARY KEY ( NB_CUR_IDN ) ;

CREATE TABLE TB_ADM_DEPENDENCIA_ACADEMICA
  (
    NB_DEP_IDN      NUMBER (10) NOT NULL ,
    VR_DEP_NOMBRE   VARCHAR2 (100 BYTE) NOT NULL ,
    NB_DEPPADRE_IDN NUMBER (10) ,
    NB_UNI_IDN      NUMBER (10) NOT NULL ,
    VR_TDP_CODIGO   VARCHAR2 (4 BYTE) NOT NULL
  ) ;
ALTER TABLE TB_ADM_DEPENDENCIA_ACADEMICA ADD CONSTRAINT TB_GEN_DEPEN_ACADE_PK PRIMARY KEY ( NB_DEP_IDN ) ;

CREATE TABLE TB_ADM_DOCENTE
  (
    NB_DOC_IDN            NUMBER (10) NOT NULL ,
    NB_PER_IDN            NUMBER (10) NOT NULL ,
    VR_DOC_IDENTIFICACION VARCHAR2 (12 BYTE) NOT NULL ,
    VR_DOC_NOMBRES        VARCHAR2 (255 BYTE) NOT NULL ,
    VR_DOC_CELULAR        VARCHAR2 (50 BYTE) ,
    VR_DOC_EMAIL          VARCHAR2 (100 BYTE) ,
    VR_ADTUSUARIO         VARCHAR2 (32 BYTE) ,
    DT_ADTFECHA           DATE
  ) ;
ALTER TABLE TB_ADM_DOCENTE ADD CONSTRAINT DOCENTE_PK PRIMARY KEY ( NB_DOC_IDN ) ;

CREATE TABLE TB_ADM_DOCENTESXDEPENDENCIA
  (
    NB_DPD_IDN             NUMBER (10) NOT NULL ,
    NB_DOC_IDN             NUMBER (10) NOT NULL ,
    NB_DEP_IDN             NUMBER (10) NOT NULL ,
    VR_DPD_TIPOVINCULACION VARCHAR2 (50)
  ) ;
ALTER TABLE TB_ADM_DOCENTESXDEPENDENCIA ADD CONSTRAINT TB_ADM_DOCENTESXDEPENDENCIA_PK PRIMARY KEY ( NB_DPD_IDN ) ;

CREATE TABLE TB_ADM_ESTADO_SEMESTRE
  (
    VR_ESM_CODIGO      VARCHAR2 (5 BYTE) NOT NULL ,
    VR_ESM_DESCRIPCION VARCHAR2 (20 BYTE) NOT NULL
  ) ;
ALTER TABLE TB_ADM_ESTADO_SEMESTRE ADD CONSTRAINT GEN_TB_ESTADO_SEMESTRE_PK PRIMARY KEY ( VR_ESM_CODIGO ) ;

CREATE TABLE TB_ADM_ESTUDIANTE
  (
    NB_EST_IDN        NUMBER (10) NOT NULL ,
    NB_PER_IDN        NUMBER (10) NOT NULL ,
    VR_CODIGOINTERNNO VARCHAR2 (10 CHAR)
  ) ;
ALTER TABLE TB_ADM_ESTUDIANTE ADD CONSTRAINT ESTUDIANTE_PK PRIMARY KEY ( NB_EST_IDN ) ;

CREATE TABLE TB_ADM_GRUPO
  (
    NB_GPO_IDN     NUMBER (10) NOT NULL ,
    VR_GPO_NUMERO  VARCHAR2 (3 CHAR) NOT NULL ,
    VR_GPO_HORARIO VARCHAR2 (50 BYTE) ,
    VR_ADTUSUARIO  VARCHAR2 (32 BYTE) ,
    DT_ADTFECHA    DATE
  ) ;
ALTER TABLE TB_ADM_GRUPO ADD CONSTRAINT GRUPO_PK PRIMARY KEY ( NB_GPO_IDN ) ;

CREATE TABLE TB_ADM_MATRICULA
  (
    NB_MAT_IDN NUMBER (10) NOT NULL ,
    NB_GRU_IDN NUMBER (10) NOT NULL ,
    NB_EST_IDN NUMBER (10) NOT NULL ,
    NB_DEP_IDN NUMBER (10) NOT NULL ,
    NB_SEM_IDN NUMBER (10) NOT NULL
  ) ;
ALTER TABLE TB_ADM_MATRICULA ADD CONSTRAINT MATRICULA_PK PRIMARY KEY ( NB_MAT_IDN ) ;

CREATE TABLE TB_ADM_MODALIDAD_CURSO
  (
    BN_MCU_IDN         NUMBER (10) NOT NULL ,
    VR_MCU_CODIGO      VARCHAR2 (5 BYTE) NOT NULL ,
    VR_MCU_DESCRIPCION VARCHAR2 (50 BYTE) NOT NULL
  ) ;
ALTER TABLE TB_ADM_MODALIDAD_CURSO ADD CONSTRAINT TB_ADM_MODALIDAD_CURSO_PK PRIMARY KEY ( BN_MCU_IDN ) ;

CREATE TABLE TB_ADM_PAISES
  (
    NB_IDN         NUMBER (10) NOT NULL ,
    VR_DESCRIPCION VARCHAR2 (20 CHAR) NOT NULL ,
    VR_CODIGO      VARCHAR2 (10 CHAR) NOT NULL ,
    VR_ADTUSUARIO  VARCHAR2 (10) ,
    DT_ADTFECHA    DATE NOT NULL
  ) ;
ALTER TABLE TB_ADM_PAISES ADD CONSTRAINT TB_ADM_PAISES_PK PRIMARY KEY ( NB_IDN ) ;

CREATE TABLE TB_ADM_PERMISOSXROL
  (
    NB_PXR_IDN        NUMBER (10) NOT NULL ,
    NB_REC_IDN        NUMBER (10) NOT NULL ,
    NB_ROL_IDN        NUMBER NOT NULL ,
    NB_PXR_ACTIVO     CHAR (1) ,
    NB_PXR_AGREGAR    CHAR (1) ,
    BN_PXR_ELIMINAR   CHAR (1) ,
    BN_PXR_ACTUALIZAR CHAR (1)
  ) ;

CREATE TABLE TB_ADM_PERSONA
  (
    NB_PER_IDN            NUMBER (10) NOT NULL ,
    VR_PER_ADTUSUARIO     VARCHAR2 (20 CHAR) NOT NULL ,
    DT_PER_ADTFECHA       DATE NOT NULL ,
    VR_PER_NOMBRES        VARCHAR2 (50 CHAR) NOT NULL ,
    VR_PER_APELLIDOS      VARCHAR2 (50) NOT NULL ,
    VR_PER_IDENTIFICACION VARCHAR2 (12 CHAR) NOT NULL ,
    VR_PER_DIRECCION      VARCHAR2 (20 CHAR) ,
    VR_PER_TELEFONO       VARCHAR2 (20 CHAR) ,
    VR_PER_EMAIL          VARCHAR2 (60 CHAR) ,
    NB_TID_IDN            NUMBER (10) NOT NULL
  ) ;
ALTER TABLE TB_ADM_PERSONA ADD CONSTRAINT TB_PERSONA_PK PRIMARY KEY ( NB_PER_IDN ) ;

CREATE TABLE TB_ADM_PROPIEDADES
  (
    NB_PRP_IDN    NUMBER (10) NOT NULL ,
    VR_PRP_CODIGO VARCHAR2 (50 BYTE) NOT NULL ,
    VR_PRP_VALOR  VARCHAR2 (255) NOT NULL ,
    NB_DEP_IDN    NUMBER (10) NOT NULL
  ) ;
ALTER TABLE TB_ADM_PROPIEDADES ADD CONSTRAINT TB_ADM_PROPIEDADES_PK PRIMARY KEY ( NB_PRP_IDN, VR_PRP_VALOR ) ;

CREATE TABLE TB_ADM_RECURSO
  (
    NB_REC_IDN      NUMBER (10) NOT NULL ,
    VR_REC_NOMBRE   VARCHAR2 (100) NOT NULL ,
    VR_REC_TIPO     VARCHAR2 (10 CHAR) NOT NULL ,
    NB_REC_RECPADRE NUMBER (10) NOT NULL
  ) ;
ALTER TABLE TB_ADM_RECURSO ADD CONSTRAINT FUNCIONALIDAD_PK PRIMARY KEY ( NB_REC_IDN ) ;

CREATE TABLE TB_ADM_ROL
  (
    NB_ROL_IDN    NUMBER NOT NULL ,
    VR_ROL_NOMBRE VARCHAR2 (50 CHAR) NOT NULL
  ) ;
ALTER TABLE TB_ADM_ROL ADD CONSTRAINT ROL_PK PRIMARY KEY ( NB_ROL_IDN ) ;

CREATE TABLE TB_ADM_SEMESTRE
  (
    NB_SEM_IDN     NUMBER (10) NOT NULL ,
    NB_SEM_AGNO    NUMBER (4) ,
    NB_SEM_PERIODO NUMBER (1) ,
    VR_ESM_CODIGO  VARCHAR2 (5 BYTE) NOT NULL ,
    NB_DEP_IDN     NUMBER (10) NOT NULL ,
    DT_ADTFECHA    DATE ,
    VR_ADTUSUARIO  VARCHAR2 (32 BYTE)
  ) ;
ALTER TABLE TB_ADM_SEMESTRE ADD CONSTRAINT SEMESTRE_PK PRIMARY KEY ( NB_SEM_IDN ) ;

CREATE TABLE TB_ADM_SEMESTREXCURSO
  (
    NB_SCU_IDN NUMBER (10) NOT NULL ,
    NB_SEM_IDN NUMBER (10) NOT NULL ,
    NB_GRU_IDN NUMBER (10) NOT NULL ,
    NB_CUR_IDN NUMBER (10) NOT NULL ,
    NB_MCU_IDN NUMBER (10) NOT NULL
  ) ;
ALTER TABLE TB_ADM_SEMESTREXCURSO ADD CONSTRAINT SEMESTREXCURSO_PK PRIMARY KEY ( NB_SCU_IDN ) ;

CREATE TABLE TB_ADM_TAREAS_PROGRAMADAS
  (
    NB_TPR_IDN     NUMBER NOT NULL ,
    VR_TPR_NOMBRE  VARCHAR2 (100 BYTE) NOT NULL ,
    VR_TPR_MANAGER VARCHAR2 (500) NOT NULL ,
    NB_TPR_ACTIVA  CHAR (1) DEFAULT '0' NOT NULL ,
    VR_ADTUSUARIO  VARCHAR2 (32 BYTE) ,
    DT_ADTFECHA    DATE ,
    NB_DEP_IDN     NUMBER (10) NOT NULL
  ) ;
CREATE UNIQUE INDEX UC_TARPROG_NOMBRE ON TB_ADM_TAREAS_PROGRAMADAS
  (
    VR_TPR_NOMBRE ASC
  )
  ;
  ALTER TABLE TB_ADM_TAREAS_PROGRAMADAS ADD CONSTRAINT TB_ACT_TARPROG_PK PRIMARY KEY ( NB_TPR_IDN ) ;

CREATE TABLE TB_ADM_TIPOIDENTIFICACION
  (
    NB_IDN         NUMBER (10) NOT NULL ,
    DT_ADTFECHA    DATE NOT NULL ,
    VR_ADTUSUARIO  VARCHAR2 (10 CHAR) NOT NULL ,
    VR_DESCRIPCION VARCHAR2 (25 CHAR) NOT NULL
  ) ;
ALTER TABLE TB_ADM_TIPOIDENTIFICACION ADD CONSTRAINT TB_ADM_TIPOIDENTIFICACION_PK PRIMARY KEY ( NB_IDN ) ;

CREATE TABLE TB_ADM_TIPO_DEPENDENCIA
  (
    VR_TDP_CODIGO VARCHAR2 (4 BYTE) NOT NULL ,
    VR_TDP_NOMBRE VARCHAR2 (50 BYTE) NOT NULL
  ) ;
ALTER TABLE TB_ADM_TIPO_DEPENDENCIA ADD CONSTRAINT TB_GEN_TIPO_DEPENDENCIA_PK PRIMARY KEY ( VR_TDP_CODIGO ) ;

CREATE TABLE TB_ADM_UNIDAD_ACADEMICA
  (
    NB_UNI_IDN    NUMBER (10) NOT NULL ,
    VR_UNI_NOMBRE VARCHAR2 (200 BYTE) NOT NULL ,
    VR_ADTUSUARIO VARCHAR2 (32 BYTE) ,
    DT_ADTFECHA   DATE
  ) ;
ALTER TABLE TB_ADM_UNIDAD_ACADEMICA ADD CONSTRAINT TB_GEN_UNIDAD_ACADEMICA_PK PRIMARY KEY ( NB_UNI_IDN ) ;

CREATE TABLE TB_ADM_UNIVERSIDADES
  (
    NB_IDM        NUMBER (10) NOT NULL ,
    VR_NOMBRE     VARCHAR2 (30 CHAR) NOT NULL ,
    DT_ADTFECHA   DATE NOT NULL ,
    VR_ADTUSUARIO VARCHAR2 (10 CHAR) NOT NULL ,
    NB_PAIS_IDN   NUMBER (10) NOT NULL
  ) ;
ALTER TABLE TB_ADM_UNIVERSIDADES ADD CONSTRAINT TB_ADM_UNIVERSIDADES_PK PRIMARY KEY ( NB_IDM ) ;

CREATE TABLE TB_ADM_USUARIO
  (
    NB_USU_IDN    NUMBER (10) NOT NULL ,
    VR_USU_LOGIN  VARCHAR2 (50 BYTE) NOT NULL ,
    NB_USU_ACTIVO NUMBER (10) NOT NULL ,
    NB_PER_IDN    NUMBER (10) NOT NULL
  ) ;
ALTER TABLE TB_ADM_USUARIO ADD CONSTRAINT USUARIO_PK PRIMARY KEY ( NB_USU_IDN ) ;

CREATE TABLE TB_ADM_USUARIOXROL
  (
    NB_UXR_IDN NUMBER (10) NOT NULL ,
    NB_ROL_IDN NUMBER NOT NULL ,
    NB_USU_IDN NUMBER (10) NOT NULL
  ) ;
ALTER TABLE TB_ADM_USUARIOXROL ADD CONSTRAINT TB_ADM_USUARIOXROL_PK PRIMARY KEY ( NB_UXR_IDN ) ;

CREATE TABLE TB_MIC_ACTA
  (
    NB_ACT_IDN NUMBER (10) NOT NULL ,
    VR_ADTUSUARIO NVARCHAR2 (32) ,
    DT_ADTFECHA DATE ,
    VR_ACT_CONTENIDO NVARCHAR2 (50) ,
    VR_ACT_ASISTENTES NVARCHAR2 (200) ,
    VR_ACT_ORDENDELDIA NVARCHAR2 (200) ,
    VR_ACT_DESARROLLO NVARCHAR2 (500) ,
    VR_ACT_FIRMAS NVARCHAR2 (100)
  ) ;
ALTER TABLE TB_MIC_ACTA ADD CONSTRAINT ACTA_PK PRIMARY KEY ( NB_ACT_IDN ) ;

CREATE TABLE TB_MIC_CURSOSXPENSUM
  (
    NB_CPE_IDN NUMBER (10) NOT NULL ,
    NB_VPE_IDN NUMBER (10) NOT NULL ,
    NB_CUR_IDN NUMBER (10) NOT NULL
  ) ;
ALTER TABLE TB_MIC_CURSOSXPENSUM ADD CONSTRAINT CURSOSXPENSUM_PK PRIMARY KEY ( NB_CPE_IDN ) ;

CREATE TABLE TB_MIC_ESTADOMIC
  (
    NB_EST_IDN NUMBER NOT NULL ,
    VR_ADTUSUARIO NVARCHAR2 (32) ,
    DT_ADTFECHA DATE ,
    VR_EST_NOMBREEST NVARCHAR2 (10)
  ) ;
ALTER TABLE TB_MIC_ESTADOMIC ADD CONSTRAINT TB_MIC_ESTADOMIC_PK PRIMARY KEY ( NB_EST_IDN ) ;

CREATE TABLE TB_MIC_EVALUACION
  (
    NB_EV_IDN NUMBER (10) NOT NULL ,
    VR_ADT_USUARIO NVARCHAR2 (32) ,
    DT_ADTFECHA DATE ,
    VR_EV_NOMBREACTIVIDAD NVARCHAR2 (32) ,
    FL_EV_PORCENTAJE FLOAT (4) ,
    DT_EV_FECHADEEVALUACION DATE
  ) ;
ALTER TABLE TB_MIC_EVALUACION ADD CONSTRAINT TB_MIC_EVALUACION_PK PRIMARY KEY ( NB_EV_IDN ) ;

CREATE TABLE TB_MIC_MICROCURRICULO
  (
    NB_MIC_IDN NUMBER NOT NULL ,
    VR_ADTUSUARIO NVARCHAR2 (32) ,
    DT_ADTFECHA                  DATE ,
    VR_MIC_NOMBRE                VARCHAR2 (32 BYTE) NOT NULL ,
    VR_MIC_VALIDABLE             VARCHAR2 (32 BYTE) ,
    NB_MIC_HORASTEORICASEMANALES NUMBER (2) ,
    NB_MIC_HORASTEROSEM          NUMBER (4) ,
    NB_MIC_NUMEROCREDITOS        NUMBER (2) ,
    NB_HORASCLASEXSEMESTRE       NUMBER (4) ,
    VR_MIC_CAMPODEFORMACION      VARCHAR2 (32 BYTE) ,
    NB_SCU_IDN                   NUMBER (10) NOT NULL ,
    NB_ACT_IDN                   NUMBER (10) NOT NULL ,
    NB_NAC_IDN                   NUMBER (10) NOT NULL ,
    VR_MIC_HABILITABLE NVARCHAR2 (14) ,
    VR_MIC_CLASIFICABLE NVARCHAR2 (14) ,
    VR_MIC_REQUISITOS NVARCHAR2 (32) ,
    VR_MIC_CORREQUISITO NVARCHAR2 (32) ,
    NB_MIC_PROGRAM NUMBER (2) NOT NULL ,
    VR_MIC_PROPOSITO NVARCHAR2 (64) ,
    VR_MIC_JUSTIFICACION NVARCHAR2 (64) ,
    VR_MIC_OBJETIVOGENERAL NVARCHAR2 (32) ,
    VR_MIC_OBJETIVOSESPECIFICOS NVARCHAR2 (64) ,
    VR_MIC_CONTENIDORESUMIDO NVARCHAR2 (100) ,
    NB_MIC_ESTADO NUMBER (2) ,
    NB_MIC_UNIDAD NUMBER (10) NOT NULL ,
    VR_MIC_BIBLIOGRAFIA NVARCHAR2 (32)
  ) ;
ALTER TABLE TB_MIC_MICROCURRICULO ADD CONSTRAINT MICROCURRICULO_PK PRIMARY KEY ( NB_MIC_IDN ) ;

CREATE TABLE TB_MIC_NUCLEOACADEMICO
  (
    NB_NAC_IDN NUMBER (10) NOT NULL ,
    VR_ADTUSUARIO NVARCHAR2 (32) ,
    DT_ADTFECHA DATE ,
    VR_NAC_NOMBRENUCLEO NVARCHAR2 (40)
  ) ;
ALTER TABLE TB_MIC_NUCLEOACADEMICO ADD CONSTRAINT NUCLEOACADEMICO_PK PRIMARY KEY ( NB_NAC_IDN ) ;

CREATE TABLE TB_MIC_UNIDADES
  (
    NB_UNI_IDN NUMBER (10) NOT NULL ,
    VR_ADTUSUARIO NVARCHAR2 (32) ,
    DT_ADTFECHA DATE ,
    VR_UNI_NOMBREUNI NVARCHAR2 (32)
  ) ;
ALTER TABLE TB_MIC_UNIDADES ADD CONSTRAINT TB_MIC_UNIDADES_PK PRIMARY KEY ( NB_UNI_IDN ) ;

CREATE TABLE TB_MIC_VERSIONPENSUM
  ( NB_VPE_IDN NUMBER (10) NOT NULL
  ) ;
ALTER TABLE TB_MIC_VERSIONPENSUM ADD CONSTRAINT VERSIONPENSUM_PK PRIMARY KEY ( NB_VPE_IDN ) ;

CREATE TABLE TB_PRD_AUTOR
  (
    NB_AUT_IDN  NUMBER (10) NOT NULL ,
    NB_PER_IDN  NUMBER (10) NOT NULL ,
    VR_PAIS_IDN NUMBER (10) NOT NULL
  ) ;
ALTER TABLE TB_PRD_AUTOR ADD CONSTRAINT AUTOR_PK PRIMARY KEY ( NB_AUT_IDN ) ;

CREATE TABLE TB_PRD_AUTORESXPRODUCCION
  (
    NB_APP_IDN NUMBER (10) NOT NULL ,
    NB_PRO_IDN NUMBER (10) NOT NULL ,
    NB_AUT_IDN NUMBER (10) NOT NULL
  ) ;
ALTER TABLE TB_PRD_AUTORESXPRODUCCION ADD CONSTRAINT AUTORESXPRODUCCION_PK PRIMARY KEY ( NB_APP_IDN ) ;

CREATE TABLE TB_PRD_CAMPOS
  (
    NB_IDN         NUMBER (10) NOT NULL ,
    VR_ADTUSUARIO  VARCHAR2 (10) NOT NULL ,
    DT_ADTFECHA    DATE NOT NULL ,
    VR_DESCRIPCION VARCHAR2 (30 CHAR) NOT NULL ,
    BL_ESTADO      CHAR (1) NOT NULL
  ) ;
ALTER TABLE TB_PRD_CAMPOS ADD CONSTRAINT TB_CAMPOS_PK PRIMARY KEY ( NB_IDN ) ;

CREATE TABLE TB_PRD_DETALLEPRODUCIONES
  (
    NB_IDN                      NUMBER (10) NOT NULL ,
    NB_PRODUCCION_IDN           NUMBER (10) NOT NULL ,
    NB_TIPOPRODUCCIONCAMPOS_IDN NUMBER (10) NOT NULL ,
    VR_VALOR                    VARCHAR2 (20 CHAR) ,
    BL_ESTADO                   CHAR (1) NOT NULL ,
    VR_ADTUSUARIO               VARCHAR2 (10 CHAR) NOT NULL ,
    DT_ADTFECHA                 DATE NOT NULL
  ) ;
ALTER TABLE TB_PRD_DETALLEPRODUCIONES ADD CONSTRAINT TB_PRD_DETALLEPRODUCIONES_PK PRIMARY KEY ( NB_IDN ) ;

CREATE TABLE TB_PRD_GRUPOINVESTIGACION
  (
    NB_IDN           NUMBER (10) NOT NULL ,
    VR_NOMBRE        VARCHAR2 (100 CHAR) NOT NULL ,
    VR_ABREVIATURA   VARCHAR2 (20 CHAR) ,
    DT_FECHACREACION DATE NOT NULL ,
    NB_DIRECTOR      NUMBER (10) NOT NULL ,
    BL_ESTADO        CHAR (1) NOT NULL ,
    VR_ADTUSUARIO    VARCHAR2 (10 CHAR) NOT NULL ,
    DT_ADTFECHA      DATE NOT NULL
  ) ;
ALTER TABLE TB_PRD_GRUPOINVESTIGACION ADD CONSTRAINT GRUPOINVESTIGACION_PK PRIMARY KEY ( NB_IDN ) ;

CREATE TABLE TB_PRD_MIEMBROSXGRUPO
  (
    NB_MIE_IDN NUMBER (10) NOT NULL ,
    NB_GPI_IDN NUMBER (10) NOT NULL ,
    NB_PER_IDN NUMBER (10) NOT NULL
  ) ;
ALTER TABLE TB_PRD_MIEMBROSXGRUPO ADD CONSTRAINT MIEMBROS_PK PRIMARY KEY ( NB_MIE_IDN ) ;

CREATE TABLE TB_PRD_PRODUCCION
  (
    NB_IDN              NUMBER (10) NOT NULL ,
    VR_NOMBREPRODUCCION VARCHAR2 (100 CHAR) NOT NULL ,
    DT_FECHAPUBLICACION DATE NOT NULL ,
    BL_ESTADO           CHAR (1) NOT NULL ,
    NB_TPR_IDN          NUMBER (10) NOT NULL ,
    DT_ADTFECHA         DATE NOT NULL ,
    VR_ADTUSUARIO       VARCHAR2 (10 CHAR) NOT NULL
  ) ;
ALTER TABLE TB_PRD_PRODUCCION ADD CONSTRAINT PRODUCCION_PK PRIMARY KEY ( NB_IDN ) ;

CREATE TABLE TB_PRD_TIPOPRODUCCION
  (
    NB_IDN         NUMBER (10) NOT NULL ,
    VR_DESCRIPCION VARCHAR2 (20) NOT NULL ,
    BL_ESTADO      CHAR (1) NOT NULL ,
    VR_ADTUSUARIO  VARCHAR2 (10) NOT NULL ,
    DT_ADTFECHA    DATE NOT NULL
  ) ;
ALTER TABLE TB_PRD_TIPOPRODUCCION ADD CONSTRAINT TIPOPRODUCCION_PK PRIMARY KEY ( NB_IDN ) ;

CREATE TABLE TB_PRD_TIPOPRODUCIONESXCAMPO
  (
    NB_IDN                NUMBER (10) NOT NULL ,
    VR_ADTUSUARIO         VARCHAR2 (10 CHAR) NOT NULL ,
    DT_ADTFECHA           DATE NOT NULL ,
    NB_TIPOPRODUCCION_IDN NUMBER (10) NOT NULL ,
    NB_CAMPO_IDN          NUMBER (10) NOT NULL
  ) ;
ALTER TABLE TB_PRD_TIPOPRODUCIONESXCAMPO ADD CONSTRAINT TB_PDR_TIPOPRODUCXCAMPO_PK PRIMARY KEY ( NB_IDN ) ;

ALTER TABLE TB_PRD_AUTORESXPRODUCCION ADD CONSTRAINT AUTORESXPRODUCCION_AUTOR_FK FOREIGN KEY ( NB_AUT_IDN ) REFERENCES TB_PRD_AUTOR ( NB_AUT_IDN ) ;

ALTER TABLE TB_PRD_AUTORESXPRODUCCION ADD CONSTRAINT AUTORESXPRODUCCION_PRODUC_FK FOREIGN KEY ( NB_PRO_IDN ) REFERENCES TB_PRD_PRODUCCION ( NB_IDN ) ;

ALTER TABLE TB_PRD_AUTOR ADD CONSTRAINT AUTOR_PERSONA_FK FOREIGN KEY ( NB_PER_IDN ) REFERENCES TB_ADM_PERSONA ( NB_PER_IDN ) ;

ALTER TABLE TB_MIC_CURSOSXPENSUM ADD CONSTRAINT CURSOSXPENSUM_CURSO_FK FOREIGN KEY ( NB_CUR_IDN ) REFERENCES TB_ADM_CURSO ( NB_CUR_IDN ) ;

ALTER TABLE TB_MIC_CURSOSXPENSUM ADD CONSTRAINT CURSOSXPENSUM_VERSIONPENSUM_FK FOREIGN KEY ( NB_VPE_IDN ) REFERENCES TB_MIC_VERSIONPENSUM ( NB_VPE_IDN ) ;

ALTER TABLE TB_ADM_CURSO ADD CONSTRAINT CURSO_TB_GEN_DEPEN_ACAD_FK FOREIGN KEY ( BN_DEP_IDN ) REFERENCES TB_ADM_DEPENDENCIA_ACADEMICA ( NB_DEP_IDN ) ;

ALTER TABLE TB_ACT_DOCENTEXGRUPO ADD CONSTRAINT DOCENTEXGRUPO_DOCENTE_FK FOREIGN KEY ( NB_DOC_IDN ) REFERENCES TB_ADM_DOCENTE ( NB_DOC_IDN ) ;

ALTER TABLE TB_ACT_DOCENTEXGRUPO ADD CONSTRAINT DOCENTEXGRUPO_GRUPO_FK FOREIGN KEY ( NB_GPO_IDN ) REFERENCES TB_ADM_GRUPO ( NB_GPO_IDN ) ;

ALTER TABLE TB_ADM_DOCENTE ADD CONSTRAINT DOCENTE_PERSONA_FK FOREIGN KEY ( NB_PER_IDN ) REFERENCES TB_ADM_PERSONA ( NB_PER_IDN ) ;

ALTER TABLE TB_ADM_ESTUDIANTE ADD CONSTRAINT ESTUDIANTE_PERSONA_FK FOREIGN KEY ( NB_PER_IDN ) REFERENCES TB_ADM_PERSONA ( NB_PER_IDN ) ;

ALTER TABLE TB_ADM_MATRICULA ADD CONSTRAINT MATRICULA_ESTUDIANTE_FK FOREIGN KEY ( NB_EST_IDN ) REFERENCES TB_ADM_ESTUDIANTE ( NB_EST_IDN ) ;

ALTER TABLE TB_ADM_MATRICULA ADD CONSTRAINT MATRICULA_GRUPO_FK FOREIGN KEY ( NB_GRU_IDN ) REFERENCES TB_ADM_GRUPO ( NB_GPO_IDN ) ;

ALTER TABLE TB_ADM_MATRICULA ADD CONSTRAINT MATRICULA_TB_GEN_DEPEN_ACAD_FK FOREIGN KEY ( NB_DEP_IDN ) REFERENCES TB_ADM_DEPENDENCIA_ACADEMICA ( NB_DEP_IDN ) ;

ALTER TABLE TB_MIC_MICROCURRICULO ADD CONSTRAINT MICROCURRICULO_ACTA_FK FOREIGN KEY ( NB_ACT_IDN ) REFERENCES TB_MIC_ACTA ( NB_ACT_IDN ) ;

ALTER TABLE TB_MIC_MICROCURRICULO ADD CONSTRAINT MICRO_NUCLEOACADEMICO_FK FOREIGN KEY ( NB_NAC_IDN ) REFERENCES TB_MIC_NUCLEOACADEMICO ( NB_NAC_IDN ) ;

ALTER TABLE TB_MIC_MICROCURRICULO ADD CONSTRAINT MICRO_SEMESTREXCURSO_FK FOREIGN KEY ( NB_SCU_IDN ) REFERENCES TB_ADM_SEMESTREXCURSO ( NB_SCU_IDN ) ;

ALTER TABLE TB_PRD_MIEMBROSXGRUPO ADD CONSTRAINT MIEMBROS_GRUPOINVESTIGACION_FK FOREIGN KEY ( NB_GPI_IDN ) REFERENCES TB_PRD_GRUPOINVESTIGACION ( NB_IDN ) ;

ALTER TABLE TB_PRD_MIEMBROSXGRUPO ADD CONSTRAINT MIEMBROS_PERSONA_FK FOREIGN KEY ( NB_PER_IDN ) REFERENCES TB_ADM_PERSONA ( NB_PER_IDN ) ;

ALTER TABLE TB_ADM_PERMISOSXROL ADD CONSTRAINT PERMISOS_FUNCIONALIDAD_FK FOREIGN KEY ( NB_REC_IDN ) REFERENCES TB_ADM_RECURSO ( NB_REC_IDN ) ;

ALTER TABLE TB_ADM_PERMISOSXROL ADD CONSTRAINT PERMISOS_ROL_FK FOREIGN KEY ( NB_ROL_IDN ) REFERENCES TB_ADM_ROL ( NB_ROL_IDN ) ;

ALTER TABLE TB_PRD_PRODUCCION ADD CONSTRAINT PRODUCCION_TIPOPRODUCCION_FK FOREIGN KEY ( NB_TPR_IDN ) REFERENCES TB_PRD_TIPOPRODUCCION ( NB_IDN ) ;

ALTER TABLE TB_ACT_REPORTEACTIVIDAD ADD CONSTRAINT REPORTEACTIVIDAD_ACTIVIDAD_FK FOREIGN KEY ( NB_TAC_IDN ) REFERENCES TB_ACT_TIPO_ACTIVIDAD ( NB_TAC_IDN ) ;

ALTER TABLE TB_ACT_REPORTEACTIVIDAD ADD CONSTRAINT REPORTEACT_DOCENTEXGRUPO_FK FOREIGN KEY ( NB_DOG_IDN ) REFERENCES TB_ACT_DOCENTEXGRUPO ( NB_DOG_IDN ) ;

ALTER TABLE TB_ADM_SEMESTREXCURSO ADD CONSTRAINT SEMESTREXCURSO_CURSO_FK FOREIGN KEY ( NB_CUR_IDN ) REFERENCES TB_ADM_CURSO ( NB_CUR_IDN ) ;

ALTER TABLE TB_ADM_SEMESTREXCURSO ADD CONSTRAINT SEMESTREXCURSO_GRUPO_FK FOREIGN KEY ( NB_GRU_IDN ) REFERENCES TB_ADM_GRUPO ( NB_GPO_IDN ) ;

ALTER TABLE TB_ADM_SEMESTREXCURSO ADD CONSTRAINT SEMESTREXCURSO_SEMESTRE_FK FOREIGN KEY ( NB_SEM_IDN ) REFERENCES TB_ADM_SEMESTRE ( NB_SEM_IDN ) ;

ALTER TABLE TB_ADM_SEMESTRE ADD CONSTRAINT SEM_GEN_TB_ESTADO_SEM_FK FOREIGN KEY ( VR_ESM_CODIGO ) REFERENCES TB_ADM_ESTADO_SEMESTRE ( VR_ESM_CODIGO ) ;

ALTER TABLE TB_ADM_TAREAS_PROGRAMADAS ADD CONSTRAINT TB_ACT_ALER_TB_ADM_DEP_ACAD_FK FOREIGN KEY ( NB_DEP_IDN ) REFERENCES TB_ADM_DEPENDENCIA_ACADEMICA ( NB_DEP_IDN ) ;

ALTER TABLE TB_ADM_PERSONA ADD CONSTRAINT TB_ADM_PER_TB_ADM_TIPOID_FK FOREIGN KEY ( NB_TID_IDN ) REFERENCES TB_ADM_TIPOIDENTIFICACION ( NB_IDN ) ;

ALTER TABLE TB_ADM_PROPIEDADES ADD CONSTRAINT TB_ADM_PROP_TB_ADM_DEP_ACAD_FK FOREIGN KEY ( NB_DEP_IDN ) REFERENCES TB_ADM_DEPENDENCIA_ACADEMICA ( NB_DEP_IDN ) ;

ALTER TABLE TB_ADM_RECURSO ADD CONSTRAINT TB_ADM_REC_TB_ADM_REC_FK FOREIGN KEY ( NB_REC_RECPADRE ) REFERENCES TB_ADM_RECURSO ( NB_REC_IDN ) ;

ALTER TABLE TB_ADM_UNIVERSIDADES ADD CONSTRAINT TB_ADM_UNIV_TB_ADM_PAIS_FK FOREIGN KEY ( NB_PAIS_IDN ) REFERENCES TB_ADM_PAISES ( NB_IDN ) ;

ALTER TABLE TB_ADM_USUARIOXROL ADD CONSTRAINT TB_ADM_USUARIOXROL_ROL_FK FOREIGN KEY ( NB_ROL_IDN ) REFERENCES TB_ADM_ROL ( NB_ROL_IDN ) ;

ALTER TABLE TB_ADM_DOCENTESXDEPENDENCIA ADD CONSTRAINT TB_AD_DCTXDEP_TB_AD_DCT_FK FOREIGN KEY ( NB_DOC_IDN ) REFERENCES TB_ADM_DOCENTE ( NB_DOC_IDN ) ;

ALTER TABLE TB_ADM_DOCENTESXDEPENDENCIA ADD CONSTRAINT TB_AD_DCTXDEP_TB_AD_DEP_AC_FK FOREIGN KEY ( NB_DEP_IDN ) REFERENCES TB_ADM_DEPENDENCIA_ACADEMICA ( NB_DEP_IDN ) ;

ALTER TABLE TB_ADM_SEMESTRE ADD CONSTRAINT TB_AD_SEM_TB_AD_DEP_ACA_FK FOREIGN KEY ( NB_DEP_IDN ) REFERENCES TB_ADM_DEPENDENCIA_ACADEMICA ( NB_DEP_IDN ) ;

ALTER TABLE TB_ADM_SEMESTREXCURSO ADD CONSTRAINT TB_AD_SEXCU_TB_AD_MOD_CUR_FK FOREIGN KEY ( NB_MCU_IDN ) REFERENCES TB_ADM_MODALIDAD_CURSO ( BN_MCU_IDN ) ;

ALTER TABLE TB_ADM_USUARIOXROL ADD CONSTRAINT TB_AD_USUXROL_TB_AD_USU_FK FOREIGN KEY ( NB_USU_IDN ) REFERENCES TB_ADM_USUARIO ( NB_USU_IDN ) ;

ALTER TABLE TB_ADM_MATRICULA ADD CONSTRAINT TB_GB_MATRICUL_TB_GEN_SEMES_FK FOREIGN KEY ( NB_SEM_IDN ) REFERENCES TB_ADM_SEMESTRE ( NB_SEM_IDN ) ;

ALTER TABLE TB_ADM_DEPENDENCIA_ACADEMICA ADD CONSTRAINT TB_GEN_DE_AC_TB_GEN_DE_AC_FK FOREIGN KEY ( NB_DEPPADRE_IDN ) REFERENCES TB_ADM_DEPENDENCIA_ACADEMICA ( NB_DEP_IDN ) ;

ALTER TABLE TB_ADM_DEPENDENCIA_ACADEMICA ADD CONSTRAINT TB_GEN_DE_AC_TB_GEN_UNI_AC_FK FOREIGN KEY ( NB_UNI_IDN ) REFERENCES TB_ADM_UNIDAD_ACADEMICA ( NB_UNI_IDN ) ;

ALTER TABLE TB_ADM_DEPENDENCIA_ACADEMICA ADD CONSTRAINT TB_GE_DE_AC_TB_GE_TIP_DE_FK FOREIGN KEY ( VR_TDP_CODIGO ) REFERENCES TB_ADM_TIPO_DEPENDENCIA ( VR_TDP_CODIGO ) ;

ALTER TABLE TB_PRD_GRUPOINVESTIGACION ADD CONSTRAINT TB_MIC_GRUINVE_TB_ADM_PER_FK FOREIGN KEY ( NB_DIRECTOR ) REFERENCES TB_ADM_PERSONA ( NB_PER_IDN ) ;

ALTER TABLE TB_MIC_MICROCURRICULO ADD CONSTRAINT TB_MIC_MICRO_TB_MIC_EST_FK FOREIGN KEY ( NB_MIC_IDN ) REFERENCES TB_MIC_ESTADOMIC ( NB_EST_IDN ) ;

ALTER TABLE TB_MIC_MICROCURRICULO ADD CONSTRAINT TB_MIC_MICRO_TB_MIC_EVAL_FK FOREIGN KEY ( NB_MIC_UNIDAD ) REFERENCES TB_MIC_EVALUACION ( NB_EV_IDN ) ;

ALTER TABLE TB_MIC_MICROCURRICULO ADD CONSTRAINT TB_MIC_MICRO_TB_MIC_UNID_FK FOREIGN KEY ( NB_MIC_UNIDAD ) REFERENCES TB_MIC_UNIDADES ( NB_UNI_IDN ) ;

ALTER TABLE TB_PRD_TIPOPRODUCIONESXCAMPO ADD CONSTRAINT TB_PDR_PRDXCAM_TB_PRD_CAMP_FK FOREIGN KEY ( NB_CAMPO_IDN ) REFERENCES TB_PRD_CAMPOS ( NB_IDN ) ;

ALTER TABLE TB_PRD_TIPOPRODUCIONESXCAMPO ADD CONSTRAINT TB_PDR_PRDXCAM_TN_PRD_PRO_FK FOREIGN KEY ( NB_TIPOPRODUCCION_IDN ) REFERENCES TB_PRD_TIPOPRODUCCION ( NB_IDN ) ;

ALTER TABLE TB_PRD_AUTOR ADD CONSTRAINT TB_PRD_AUTOR_TB_ADM_PAISES_FK FOREIGN KEY ( VR_PAIS_IDN ) REFERENCES TB_ADM_PAISES ( NB_IDN ) ;

ALTER TABLE TB_PRD_DETALLEPRODUCIONES ADD CONSTRAINT TB_PRD_DETPRD_TB_PRD_PRD_FK FOREIGN KEY ( NB_PRODUCCION_IDN ) REFERENCES TB_PRD_PRODUCCION ( NB_IDN ) ;

ALTER TABLE TB_PRD_DETALLEPRODUCIONES ADD CONSTRAINT TB_PRD_DETPRD_TB_PRD_PRXCA_FK FOREIGN KEY ( NB_TIPOPRODUCCIONCAMPOS_IDN ) REFERENCES TB_PRD_TIPOPRODUCIONESXCAMPO ( NB_IDN ) ;

ALTER TABLE TB_ADM_USUARIO ADD CONSTRAINT USUARIO_PERSONA_FK FOREIGN KEY ( NB_PER_IDN ) REFERENCES TB_ADM_PERSONA ( NB_PER_IDN ) ;



-- Informe de Resumen de Oracle SQL Developer Data Modeler: 
-- 
-- CREATE TABLE                            44
-- CREATE INDEX                             1
-- ALTER TABLE                             95
-- CREATE VIEW                              0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                          12
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                         12
-- CREATE MATERIALIZED VIEW                 0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
