package com.proint1.udea.administracion.entidades.terceros;

import com.proint1.udea.administracion.entidades.dependencias.DependenciaAcademica;
// default package
// Generated 10-may-2014 11:58:30 by Hibernate Tools 3.4.0.CR1

/**
 * TbAdmDocentesxdependencia generated by hbm2java
 */
public class DocenteDependencia implements java.io.Serializable {

	private long nbDpdIdn;
	private Docente tbAdmDocente;
	private DependenciaAcademica tbAdmDependenciaAcademica;
	private String vrDpdTipovinculacion;

	public DocenteDependencia() {
	}

	public DocenteDependencia(long nbDpdIdn, Docente tbAdmDocente,
			DependenciaAcademica tbAdmDependenciaAcademica) {
		this.nbDpdIdn = nbDpdIdn;
		this.tbAdmDocente = tbAdmDocente;
		this.tbAdmDependenciaAcademica = tbAdmDependenciaAcademica;
	}

	public DocenteDependencia(long nbDpdIdn, Docente tbAdmDocente,
			DependenciaAcademica tbAdmDependenciaAcademica,
			String vrDpdTipovinculacion) {
		this.nbDpdIdn = nbDpdIdn;
		this.tbAdmDocente = tbAdmDocente;
		this.tbAdmDependenciaAcademica = tbAdmDependenciaAcademica;
		this.vrDpdTipovinculacion = vrDpdTipovinculacion;
	}

	public long getNbDpdIdn() {
		return this.nbDpdIdn;
	}

	public void setNbDpdIdn(long nbDpdIdn) {
		this.nbDpdIdn = nbDpdIdn;
	}

	public Docente getTbAdmDocente() {
		return this.tbAdmDocente;
	}

	public void setTbAdmDocente(Docente tbAdmDocente) {
		this.tbAdmDocente = tbAdmDocente;
	}

	public DependenciaAcademica getTbAdmDependenciaAcademica() {
		return this.tbAdmDependenciaAcademica;
	}

	public void setTbAdmDependenciaAcademica(
			DependenciaAcademica tbAdmDependenciaAcademica) {
		this.tbAdmDependenciaAcademica = tbAdmDependenciaAcademica;
	}

	public String getVrDpdTipovinculacion() {
		return this.vrDpdTipovinculacion;
	}

	public void setVrDpdTipovinculacion(String vrDpdTipovinculacion) {
		this.vrDpdTipovinculacion = vrDpdTipovinculacion;
	}

}
